[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
lib_deps = 
    adafruit/Adafruit TinyUSB Library@^3.3.4

build_flags =
    -D CFG_TUSB_CONFIG_FILE=\"tusb_config.h\"
    -D USE_TINYUSB